name: adaptive

channels:
  - conda-forge

dependencies:
  - python
  - sortedcollections
  - scikit-optimize
  - scikit-learn
  - scipy
  - holoviews=1.13.3
  - bokeh=2.2.1
  - plotly
  - ipywidgets
  - jupyter_sphinx
  - atomicwrites
  - sphinx_fontawesome
  - sphinx
  - m2r2
  - sphinx_rtd_theme
