name: adaptive

channels:
  - conda-forge

dependencies:
  - python
  - sortedcollections
  - scikit-optimize
  - scipy
  - holoviews
  - bokeh
  - plotly
  - ipywidgets
  - jupyter_sphinx
  - atomicwrites
  - sphinx_fontawesome
  - sphinx
  - m2r2
  - pip:
    - sphinx_rtd_theme
