name: adaptive

channels:
  - conda-forge

dependencies:
  - python
  - sortedcollections
  - scikit-optimize
  - scikit-learn <=0.23.1  # because of https://github.com/scikit-optimize/scikit-optimize/issues/931, remove dep when fixed
  - scipy
  - holoviews
  - bokeh
  - plotly
  - ipywidgets
  - jupyter_sphinx ==0.2.3 # because of https://github.com/jupyter/jupyter-sphinx/issues/126
  - atomicwrites
  - sphinx_fontawesome
  - sphinx
  - m2r2
  - pip:
    - sphinx_rtd_theme
